services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8187:8080"
    volumes:
      - ~/core-key:/root/core-key
      - ~/core-password:/root/core-password
    networks:
      - webnet

  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8143:443"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
