# compile server
FROM openjdk:17-jdk AS builder

RUN microdnf install findutils

WORKDIR /app

COPY ./server .

RUN --mount=type=cache,target=/root/.gradle \
    sh prod.sh

# pack
FROM openjdk:17

WORKDIR /app

COPY --from=builder /app/build/output/*.jar .

# 使用caddy 反向代理，不需要开启ssl
CMD java -jar *.jar --server.port=8080 --server.ssl.enabled=false